title: P.Sherman
author: Joseph "P.Sherman" G
theme: minima
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  P.Sherman likes to fish.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
